{
 "title": "Parametros",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Report Control Panel",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "content": "<style>\r\n.button {\r\n  background-color: #4CAF50;\r\n  border: none;\r\n  color: white;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  display: inline-block;\r\n  cursor: pointer;\r\n}\r\n</style>\r\n\r\n<button class=\"button\" onClick=\"window.open('grafana:3000');\">\r\n     <span class=\"icon\">Raw Job</span>\r\n</button>\r\n</br>\r\n <span></span>\r\n</br>\r\n<label for=\"report\">Choose a report for kpi:</label>\r\n<select id=\"reportInput\">\r\n  <option value=\"bitrate\">bitrate</option>\r\n  <option value=\"ImpactingEvents\">ImpactingEvents</option>\r\n  <option value=\"TCPLoss\">TCPLoss</option>\r\n</select>\r\n\r\n<button type=\"button\" class=\"button\" onclick=\"getReportInput();\">Create Report</button>\r\n</br>\r\n <span></span>\r\n</br>\r\n\r\n<label for=\"reportparameter\">Choose a parameter to change for the selected kpi:</label>\r\n<select id=\"reportparameterInput\">\r\n  <option value=\"timeReport\">timeReport</option>\r\n  <option value=\"timewindowReport\">timewindowReport</option>\r\n</select>\r\n\r\n <input type=\"text\" placeholder=\"value...\" id=\"myInput\">\r\n  <button type=\"button\"  class=\"button\">Change parameter</button>\r\n<script>\r\n    function getReportInput(){\r\n        // Selecting the input element and get its value \r\n        var inputVal = document.getElementById(\"reportInput\").value;\r\n        \r\n        // Displaying the value\r\n        window.open('http://www.example.com/report/'+inputVal)\r\n    }\r\n    \r\n    \r\n      function getProfileInput(){\r\n        // Selecting the input element and get its value \r\n        var inputVal = document.getElementById(\"profileInput\").value;\r\n        \r\n        // Displaying the value\r\n        window.open('http://www.example.com/profile/'+inputVal)\r\n    }\r\n</script>\r\n"
  },
  {
   "title": "Profile Control Panel",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "content": "<style>\r\n.button {\r\n  background-color: #4CAF50;\r\n  border: none;\r\n  color: white;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  display: inline-block;\r\n  cursor: pointer;\r\n}\r\n</style>\r\n\r\n<label for=\"profile\">Choose a profile for kpi:</label>\r\n<select id=\"profileInput\">\r\n  <option value=\"bitrate\">bitrate</option>\r\n  <option value=\"ImpactingEvents\">ImpactingEvents</option>\r\n  <option value=\"TCPLoss\">TCPLoss</option>\r\n</select>\r\n\r\n<button type=\"button\" class=\"button\" onclick=\"getProfileInput();\">Create Profile</button>\r\n\r\n</br>\r\n <span></span>\r\n</br>\r\n<label for=\"profileparameter\">Choose a parameter to change for the selected kpi:</label>\r\n<select id=\"profileparameterInput\">\r\n<option value=\"timeProfile\">timeProfile</option>\r\n<option value=\"valMax\">valMax</option>\r\n<option value=\"valMin\">valMin</option>\r\n\r\n</select>\r\n\r\n <input type=\"text\" placeholder=\"value...\" id=\"myInput\">\r\n \r\n \r\n  <button type=\"button\"  class=\"button\">Change parameter</button>\r\n<script>\r\n      function getProfileInput(){\r\n        // Selecting the input element and get its value \r\n        var inputVal = document.getElementById(\"profileInput\").value;\r\n        \r\n        // Displaying the value\r\n        window.open('http://www.example.com/profile/'+inputVal)\r\n    }\r\n</script>\r\n"
  },
  {
   "title": "Parameters",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * from Parametros.Parametro;"
    }
   ]
  },
  {
   "title": "Average BitRate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  KPI AS metric,\n  value\nFROM ProfileCache\nWHERE\n  $__timeFilter(TIMESTAMP) AND\n  KPI = 'bitrate'\nORDER BY TIMESTAMP\n\n"
    }
   ]
  },
  {
   "title": "Last Occurrences",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT KPI, value from ProfileCache;"
    }
   ]
  },
  {
   "title": "BitRate Averange History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP AS \"time\",\n  value\nFROM ProfileCache\nWHERE\n  $__timeFilter(TIMESTAMP)\nORDER BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select * from Parametros.Notification"
    }
   ]
  }
 ]
}